[package]
name = "nst-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.31"}
bitcoincore-rpc = "0.18"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
simple_logger = "4.3"